baseURL: https://lammaocc.hk
title: LOCC
languageCode: en-us
DefaultContentLanguage: en
enableEmoji: true
enableGitInfo: true
enableRobotsTXT: true
canonifyURLs: true
paginate: 9
darkmode_js:
  - assets/js/darkmode.js
enableInlineShortcodes: true

markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer:
        apostrophe: '&rsquo;'
        disable: false
        ellipsis: '&hellip;'
        emDash: '&mdash;'
        enDash: '&ndash;'
        leftAngleQuote: '&laquo;'
        leftDoubleQuote: '&ldquo;'
        leftSingleQuote: '&lsquo;'
        rightAngleQuote: '&raquo;'
        rightDoubleQuote: '&rdquo;'
        rightSingleQuote: '&rsquo;'
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
      wrapStandAloneImageWithinParagraph: true
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false

params:
  author: 
  og_image: "images/pages/hero.webp"
  moto: "Lamma's best (and only) outrigger canoe club."
  description: ""
  disable_theme_toggle: false
  disable_stay_uptodate: false

  p1:
    heading: "Who are we?"
    image: "images/pages/club.webp"
    content:
      - text: "The Lamma Outrigger Canoe Club (LOCC) was founded in 2006, with two second-hand, six-person outrigger canoes and a dozen or so brave enthusiasts."
      - text: "We have made our home on Tai Wan To Beach (locally known as Power-Station Beach) in Yung Shue Wan, on Lamma Island (Hong Kong)."
  p2:
    heading: ""
    image: "images/pages/club-2.jpeg"
    content:
      - text: "18 years on, we have a fleet of four six-person canoes (OC6s), a two-person canoe (OC2), and a numerous club and personally owned OC1s (singles)"
      - text: "We've been paddling together for years, and have formed a tight-knit community of paddlers! We are always eager to get new people enjoying the sport and going out on the water!"
      - text: "We organise trainings, races, open days, and other social events!"
  p4:
    heading: "From the blog"
    content:
      - text: ""


  social_media:
    facebook:
      enabled: true
      url: 'https://www.facebook.com/groups/372875236117806/'
    instagram:
      enabled: true
      url: 'https://www.instagram.com/lammaocc/'
    youtube:
      enabled: true
      url: 'https://youtube.com/@lammaocc'

menu:
  main:
    - identifier: blog
      name: Blog
      url: /posts/
      weight: 10
  main:
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 50
  footer:
    - identifier: blog
      name: Blog
      url: /posts/
      weight: 20
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 50

markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  category: Categories
  tag: Tags

privacy:
  disqus:
    disable: false
  googleAnalytics:
    anonymizeIP: true
    disable: false
    respectDoNotTrack: false
    useSessionStorage: false
  instagram:
    disable: false
    simple: false
  twitter:
    disable: false
    enableDNT: false
    simple: false
  vimeo:
    disable: false
    enableDNT: false
    simple: false
  youtube:
    disable: false
    privacyEnhanced: true

module:
  hugoVersion:
    extended: true
    min: "0.104.0"
