backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: "assets/images/featured" # Media files will be stored in the repo under static/images/uploads
public_folder: "assets/images/featured" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/posts/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "featured_image", widget: "image"}
      - {label: "Date", name: "date", widget: "datetime", time_format: false}
      - {label: "Tags", name: "tags", widget: "string"}
      - {label: "Summary", name: "summary", widget: "markdown"}
      - {label: "Body", name: "body", widget: "markdown"}

